sudo: required
services:
  - docker

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
  - "wget -d --head='Host: localhost' --referer=https://go.sap.com https://d149oh3iywgk04.cloudfront.net/hanaexpress/HANA2latest/linuxx86-64/tar/hxe.tgz"
  # - java -jar HXEDownloadManager-01.jar
  # - curl -v -OLS https://d149oh3iywgk04.cloudfront.net/hanaexpress/HANA2latest/linuxx86-64/tar/hxe.tgz
  # - java -jar HXEDownloadManager.jar
  
script:
  - echo "Build local image"
  - docker build -t hana .
  - docker images
  - docker run --name my-hana -d -p 5000:5000 hana
  - echo "Wait hana to start up"    
  - docker ps -a  
  - docker logs my-hana
  - docker exec -it my-hana ps -ef
  - echo "Checking hana"
  # - docker exec -it my-hana isql -U sa -P myPass -S MYSYBASE
  - docker stop my-hana
  - echo "Testing public image on Docker Hub"
  - docker run -d -p 5000:5000  --name nguoianphu-hana nguoianphu/docker-hana
  - docker ps -a
  - docker images
  - echo "Checking hana"  
  - docker logs nguoianphu-hana
  - docker exec -it nguoianphu-hana ps -ef
  # - docker exec -it nguoianphu-hana isql -U sa -P myPass -S MYSYBASE  
  - docker stop nguoianphu-hana
